version: "3.9"

services:
  frontend:
    container_name: nextjs-frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
